#!/bin/bash

. $(dirname ${0})/kestrel_functions

SPEC=${1}

validate_single_arg ${0} ${SPEC}

host=$(get_host ${SPEC})
port=$(get_port ${SPEC})
queue=$(get_queue ${SPEC})

value="$(kestrel_get ${host} ${port} "${queue}/peek")"
if [ $(strlen "${value}") -eq 0 ] ; then
  exit 2
else
  echo "${value}"
fi
exit 0
