#!/bin/bash

. $(dirname ${0})/kestrel_functions

SPEC=${1}
COUNT=${2}

if [ "x${SPEC}" = "x" ] || [ "x${COUNT}" = "x" ] ; then
  usage ${0} "[host[:port]/]queue count"
  exit 1
fi

host=$(get_host ${SPEC})
port=$(get_port ${SPEC})
queue=$(get_queue ${SPEC})

i=0
while [ $i -lt $COUNT ] ; do
  kestrel_set ${host} ${port} ${queue} value_${i}
  i=`expr $i + 1`
done

